Examples improvements
RustAudio/cpal pull request #523
Opened 2020-12-14 18:52 UTC by alexmoon

Since the Android target was added, the examples have been building as cdylibs instead of binaries. This obviously makes testing more difficult on platforms that are not Android. This PR creates a copy of the beep example specifically for building as an Android APK and sets the remaining examples back to a crate-type of bin.

This PR also adds argument parsing (using structopt) to several of the examples to allow selecting non-default devices and (for the feedback example) setting the latency. Finally, it improves error handling in the enumerate example in the case that supported_input_configs() or supported_output_configs() returns an error.

These changes make it easier to test cpal on systems with multiple audio devices.

2020-12-21 23:07 UTC, est31 requested changes

2020-12-21 23:07 UTC, est31 commented on Cargo.toml
> +crate-type = ["bin"]
Are these explicit lines needed? Can they just be removed?

2020-12-21 23:11 UTC, est31 commented
Another issue I have with this PR: before applying it, running `cargo test --no-run` showed 40 compilation units for cargo to churn through. Now it shows 60 units. Not sure it's worth the saved code. Can you maybe disable default features? I've seen this saves 4 dependencies. Further suggestions to reduce the number are welcome!

2020-12-22 00:11 UTC, alexmoon commented on Cargo.toml
> +crate-type = ["bin"]
I can remove the path and crate-type from the other examples if you want, but in the 2015 edition once one example is added to Cargo.toml all examples have to be explicitly named. See https://github.com/rust-lang/cargo/issues/5330 for details.

2020-12-22 00:14 UTC, alexmoon commented
> Another issue I have with this PR: before applying it, running `cargo test --no-run` showed 40 compilation units for cargo to churn through. Now it shows 60 units. Not sure it's worth the saved code. Can you maybe disable default features? I've seen this saves 4 dependencies. Further suggestions to reduce the number are welcome!

That's fair. If you want I can use the underlying `clap` crate instead of `structopt` which cuts the added compilation units down to 3 instead of 17 (on MacOS). It makes the code a bit more verbose (around 10-15 lines of argument parsing code at the start of `main` instead of 1 line) but otherwise works fine.

2020-12-22 01:05 UTC, est31 commented
@alexmoon migrating to clap would be great!

2020-12-22 03:12 UTC, est31 commented on Cargo.toml
> +crate-type = ["bin"]
I was mainly wondering about the explicit crate-type. Thought bin was implied.

2020-12-23 01:37 UTC, est31 approved these changes

2020-12-23 01:38 UTC, merged