wasapi: Allow both threading models and switch the default to STA
RustAudio/cpal pull request #597
Opened 2021-08-06 15:16 UTC by ishitatsuyuki

COM can prevent undefined behavior in either concurrency model by
performing marshaling when necessary. As a result, CoInitializeEx can be
called with either concurrency model, and in this case STA provides better
compatibility with other code requiring STA, e.g. ASIO backend or winit
drag-and-drop.

To dive into the detail, the entry point of WASAPI, MMDeviceEnumerator, is
registered with "both" threading model, which means that COM objects are
created with whatever the thread's concurrency model is set to. This raises
the concern that when STA is used, marshaling might make audio buffer
operations block on the main thread, breaking continuous audio processing.
However, the implementation actually uses free-threaded marshaller for
interfaces dealing with buffer operations, which effectively bypasses COM's
compatibility marshaling behavior and perform any API calls on the caller's
thread instead. Therefore, the interfaces would operate just fine on either
concurrency model.

For more details on COM's threading model, see [1].

[1] https://thrysoee.dk/InsideCOM+/ch04d.htm

Co-Authored-By: Henrik Rydgård <hrydgard@gmail.com>

Close #348
Close #504
Close #538

2021-08-06 15:17 UTC, ishitatsuyuki commented
cc @hrydgard @JoshuaBatty

2021-08-06 16:54 UTC, hrydgard approved these changes

2021-08-07 18:45 UTC, Ralith commented
Thanks for doing all that research and sorting this out, this is awesome!

2021-08-07 19:16 UTC, maroider requested changes
Echoing what @Ralith said: Thanks for fixing this long-standing issue!

I think this PR also fixes #530 and #572.

2021-08-07 19:16 UTC, maroider commented on src/host/wasapi/com.rs
> +    _ptr: *mut (),
```suggestion
    _marker: PhantomData<*mut ()>,
```

Using `PhantomData<*mut T>` avoids the need to store a pointer while still removing `Send`/`Sync`.

2021-08-07 19:16 UTC, maroider commented on src/host/wasapi/com.rs
> +        // this call can fail with RPC_E_CHANGED_MODE if another library initialized COM with MTA.
```suggestion
        // This call can fail with RPC_E_CHANGED_MODE if another library initialized COM with MTA.
```
nit: capitalization

2021-08-08 03:04 UTC, ishitatsuyuki commented
Thanks @maroider for the suggested changes!

2021-08-08 05:04 UTC, est31 approved these changes
Thanks!

2021-08-08 05:04 UTC, merged

2021-08-08 05:05 UTC, est31 commented
This is a big one. i think it warrants a new release, don't you think?

2021-08-08 06:01 UTC, ishitatsuyuki commented
Yeah, let's have a release!

2021-08-08 16:53 UTC, ishitatsuyuki commented
@est31 I don't have publish perms on crates.io, would you mind doing the release? (just a friendly reminder)

2021-08-08 17:17 UTC, est31 commented
@ishitatsuyuki I think it should be enough to file a PR that increases the version. That will trigger the auto publish machinery.

2021-08-08 17:26 UTC, ishitatsuyuki commented
Got it, will do that tomorrow unless someone beat me to it.

2021-08-08 20:37 UTC, est31 commented
0.13.4 is out: #598

2021-08-09 02:23 UTC, danwilhelm commented
@ishitatsuyuki Thanks for thoroughly researching this issue!

2021-08-09 04:06 UTC, JoshuaBatty commented
Thanks @ishitatsuyuki for doing this. Very much appreciated!