Add sample-based generation example: synth_tones
RustAudio/cpal pull request #612
Opened 2021-11-02 11:25 UTC by Wandalen

Sample-based generation of sound.

It is refactored version of the example `beep`. I bubbled up a callback to generate a sample. Also, I replaced `unwrap` with proper handling of errors. That does not add complexity because `anyhow and `?` are already in use. That's the first step I would like it was done for me to start playing with `cpal` and integrating it into my projects. 

Hopefully, it will be useful for not only me.

2021-11-02 11:32 UTC, Wandalen commented
Please let me know if any adjustments are required.

2021-11-16 14:38 UTC, est31 requested changes

2021-11-16 14:38 UTC, est31 commented on examples/synth_tones.rs
> +//
Can you remove these // ?

2021-11-16 14:38 UTC, est31 commented on examples/synth_tones.rs
> +    return Ok(());
You don't need a return statement here

2021-11-16 14:38 UTC, est31 commented on examples/synth_tones.rs
> +    combination of several tones
This can be a // comment

2021-11-16 14:38 UTC, est31 commented on examples/synth_tones.rs
> +pub fn _stream_make<T, F>(
Can you remove the leading underscore in the function name?

2021-11-16 15:57 UTC, Wandalen commented
@est31 sure! done. anything else?

2021-11-16 16:28 UTC, est31 approved these changes
Thanks!

2022-01-14 12:38 UTC, merged

2022-01-14 12:58 UTC, Wandalen commented
;)

2022-01-14 13:20 UTC, est31 commented
Sorry for the long delay, I think I've enabled CI on it and then lost track of the PR. It's a bit annoying that it doesn't ping you after CI is finished.

2022-01-14 14:29 UTC, Wandalen commented
Thanks for good open source)

2022-01-14 20:24 UTC, Ralith commented
If you set CI as required in branch prediction, you can enable automerge on CI green, which is pretty handy in these cases.