Implement BufferSize::Fixed in wasapi, and migrate wasapi to officially-supported Windows crate
RustAudio/cpal pull request #669
Opened 2022-06-03 03:00 UTC by Osspial

I migrated to `windows-rs` in this PR since exposing the buffer size range for hardware-offloaded audio processing requires `IAudioClient2`, which isn't exposed in the `winapi` crate, and `winapi` seems to be more or less unmaintained at this point.

Regarding fixed buffer sizes - `wasapi` doesn't seem to support requesting *exact* audio buffer sizes, but will always get an audio buffer that is at least the size requested. Should that be mentioned in the documentation? Also, the buffer exposed to the `data_callback` doesn't always match the size of the buffer requested, since `wasapi` incrementally updates the buffer as audio gets played, instead of updating it all at once once the buffer is cleared. I'm not sure if that's standard behavior or not but it may also be worth documenting.

Related to #544, #534, #667, and #616. @est31, you'd mentioned at https://github.com/RustAudio/cpal/issues/616#issuecomment-969904220 that `windows-rs` had some issues with cross-compilation, but from what I can tell from skimming their issue tracker the cross-compilation issues have been addressed. Are there other issues there that are unresolved?

2022-06-03 08:53 UTC, est31 commented
I haven't tried cross compiling to windows yet, but looking at windows-rs CI there seems to be no cross compilation job.

Their [contributing guide](https://github.com/microsoft/windows-rs/blob/master/.github/contributing.md) doesn't mention targetting the windows platform from Linux either.

I don't know whether they really support that feature with the love it deserves.

2022-06-03 08:57 UTC, est31 commented
I've filed an issue, let's see how they react: https://github.com/microsoft/windows-rs/issues/1799

2022-06-09 01:15 UTC, est31 commented
Okay, I guess we can switch to windows-rs. If there's an issue we can always revert the switch. There are some conflicts for the PR.

2022-06-09 21:09 UTC, Osspial commented
Merge conflicts have been resolved.

2022-06-09 21:13 UTC, est31 commented
Can you resolve them via rebase instead? It would be a pity to squash this.

2022-06-09 21:14 UTC, est31 commented
Wait no sorry disregard, it's a history that needs squashing anyways I think.

2022-06-16 22:04 UTC, Osspial commented
Does this need any more revisions, or is it good to merge?

2022-06-17 13:13 UTC, est31 commented
Stuff like this makes me worried tbh: https://github.com/omnisharp/omnisharp-vscode/issues/5276

2022-06-17 17:46 UTC, Osspial commented
That's... fair! But I think this case is materially different - if this PR were pulling in a more substantial Microsoft product I'd definitely share your concern, but they've consistently provided open access to the Windows C/C++ headers for multiple decades, even during the peak of their anti-competitive practices in the 2000s. The `windows` crate is more or less an official extension of that into the Rust ecosystem, and even with an exceedingly uncharitable view of Microsoft it doesn't square with their past behavior regarding the C headers for them to lock that down.

2022-06-18 00:28 UTC, est31 requested changes
Looks mostly good, thank you!

2022-06-18 00:28 UTC, est31 commented on src/host/wasapi/device.rs
> +        a.data1 == b.data1 && a.data2 == b.data2 && a.data3 == b.data3 && a.data4 == b.data4
while you are changing this, this could use `(a.data1, a.data2, ...) == (...)`

2022-06-18 00:28 UTC, est31 commented on src/host/wasapi/device.rs
> +                let w1: u16 = *id1.0 .0.offset(offset);
I'm not sure about this spacing here.

2022-06-18 00:30 UTC, est31 commented
@Osspial you are making good points. Let's give them a chance. If they annoy folks enough we can always switch back.

2022-06-18 17:18 UTC, Osspial commented on src/host/wasapi/device.rs
> +                let w1: u16 = *id1.0 .0.offset(offset);
That seems to be due to https://github.com/rust-lang/rustfmt/issues/4543. It's fixed if you put `version = "Two"` in `rustfmt.toml`, but that option doesn't actually work on stable `rustfmt`, so I've revised these to work around that (see https://github.com/RustAudio/cpal/pull/669/commits/e89f4d5697bafe5eeeafddd87f4f6b4786adf5b2).

2022-07-13 15:55 UTC, Osspial commented
Is this good to merge?

2022-07-13 16:50 UTC, est31 commented
@Osspial can you resolve the merge conflicts? After that it should be good to merge.

2022-07-15 01:31 UTC, Osspial commented
I'm not seeing any merge conflicts on my end.

2022-07-15 12:58 UTC, est31 approved these changes

2022-07-15 12:59 UTC, merged