Implement disconnection detection for CoreAudio on MacOS.
RustAudio/cpal pull request #707
Opened 2022-10-08 08:55 UTC by generalelectrix

Relates to #704 and #373.  Implements a very basic mechanism for polling to determine if the device underlying a CoreAudio-backed stream has been disconnected.  This definitely works, but is obviously a very platform-dependent solution as you have to unpack the underlying stream type to access it.

Feedback extremely welcome.

2022-10-08 22:00 UTC, generalelectrix commented
Perhaps a better design might involve a customizable "on device disconnect" callback, though I would need to read up a bit on the details and pitfalls of passing closures across the FFI boundary.  It looks like there is some existing code that also handles this in the implementation of `AudioUnit` in the `coreaudio-rs` crate - basically boxing the closure, converting to a raw pointer, passing that pointer into C, ensuring the closure in C does not outlive the original injection context, then re-creating the box from the raw pointer in `AudioUnit`'s `Drop` impl.

2022-10-08 22:09 UTC, est31 commented
Yeah a callback would be a dream, polling isn't nice. On the other hand, light polling, e.g. once every n seconds isn't much of an issue either.

2022-10-08 22:18 UTC, generalelectrix commented
Callback seems feasible and I think I have enough examples to make it happen!  I'll tap here for a review once I have something implemented, possibly later this evening.

2022-10-08 23:02 UTC, generalelectrix commented
Just leaving some hardware notes here for future reference.  There seemed to be a delay on the order of ~1s between unplugging the device and observing the callback fire via the console.  I did not measure this systematically.  Empirically, it looked like the input stream processor would suddenly stop calling the input handling callback as soon as the device was physically disconnected, then after a delay on the order of one second, the device disconnection message would fire and the input stream callback started getting frames again (from the current "default" device).  Testing with an old Rane TTM57SL mixer.

2022-10-09 09:50 UTC, generalelectrix commented
@est31 I implemented a convenience wrapper for registering audio object property listeners, then used that wrapper to clean up the existing (rather unsafe) mechanism for setting the sample rate.  I manually tested this and it seems to work fine.  I used this same wrapper for adding a method hook to register a callback that is called when the device is disconnected.

2022-10-09 09:54 UTC, generalelectrix commented on src/host/coreaudio/macos/mod.rs
> +    // Get the current sample rate.
Most of this code is unchanged besides replacing the property listener calls with the helper type I created, and using a channel instead of a raw pointer/polling.

2022-10-10 07:29 UTC, morajabi commented on src/host/coreaudio/macos/mod.rs
> +    pub fn set_on_disconnect<F: FnMut() -> () + 'static>(
beautiful API

2022-10-10 13:49 UTC, est31 requested changes
Looks really good! Thanks for the PR :).

2022-10-10 13:49 UTC, est31 commented on src/host/coreaudio/macos/property_listener.rs
> +            self._remove().ok();
I think `_ = ...` (or `let _ = ...`) is better than calling ok here, to ignore the error.

2022-10-10 13:49 UTC, est31 commented on src/host/coreaudio/macos/property_listener.rs
> +    fn _remove(&mut self) -> Result<(), BuildStreamError> {
Can you rename this to not have a leading _? That turns off the dead code lints. Maybe `remove_mut`?

2022-10-10 19:59 UTC, generalelectrix commented on src/host/coreaudio/macos/property_listener.rs
> +            self._remove().ok();
Heh, I'm so accustomed to "ensure every error is handled or returned" that I don't have well-formed opinions on how to ignore them 😄

2022-10-10 20:34 UTC, Ralith commented
Shouldn't this be surfaced through the existing [`StreamError::DeviceNotAvailable`](https://docs.rs/cpal/latest/cpal/enum.StreamError.html#variant.DeviceNotAvailable) in the existing error callback?

2022-10-10 20:46 UTC, est31 commented
@Ralith good point. I guess that's how the other backends expose it. @generalelectrix does that fulfill your use case? If so, would it be possible to adjust the PR? I think it's better to have portable solutions. I wasn't aware of that, sorry.

2022-10-10 21:14 UTC, generalelectrix commented
@Ralith @est31 happy to refactor but might get into the weeds.  For the other backends - when a device disconnects, does the stream terminate, calling the `error_callback` a single time with `DeviceNotAvailable`?  Or does it continue to be called repeatedly?  It seems like there is some complexity in the CoreAudio case because of the notion of a "default" device and having the output follow the "default", such that there are some cases where you may not actually want to stop the stream/send `DeviceNotAvailable` if you are opting-in to that behavior.  This seems to be implemented for the output case by this PR, though not the input case:
https://github.com/RustAudio/cpal/pull/648

2022-10-10 21:18 UTC, Ralith commented
> when a device disconnects, does the stream terminate, calling the `error_callback` a single time with `DeviceNotAvailable`?

I'm not intimately familiar with how other backends handle this, but that's what my personal expectation as a user would be. If the user wants to handle that by reverting to another device, I think it's appropriate for them to do so manually, which I imagine is more portable.

2022-10-11 10:02 UTC, generalelectrix commented
@Ralith I refactored to implement the behavior discussed above.  It required introducing shared ownership via Arc/Mutex for the error callback (so it can be called from the disconnect action) and to the overall stream entity (so it can be stopped asynchronously from the disconnect callback).  For the case where the default device was explicitly opened, no disconnect action is attached to ensure we do not break the existing contract.  This may not actually be necessary since the default device type may never issue a disconnected event, but I'm currently away from home and need to scrounge up an audio input device to test the new behavior.

2022-10-12 05:30 UTC, generalelectrix commented
I do not currently have access to an external audio input device, but I was able to test the new disconnect behavior on the output side with an external display with audio.  The feature seems to work as desired: when the default output is selected, the existing behavior of tracking the output device is preserved.  However, when a specific named device is opened, disconnecting that device causes the stream to stop and the error callback to be called with `StreamError::DeviceNotAvailable`.

2022-10-12 15:59 UTC, est31 approved these changes
Looks good!

2022-10-12 16:12 UTC, merged