Bump linux deps
RustAudio/cpal pull request #712
Opened 2022-10-20 22:13 UTC by mbodmer

2022-10-20 22:20 UTC, mbodmer commented
I don't get any clippy warnings locally. I assume it's the cargo issue here: https://github.com/rust-lang/cargo/issues/10307 workaround is to remove Cargo.lock and rebuild. Could someone with access to the build server please do this, or start a clean build.

2022-10-21 07:52 UTC, mbodmer commented
libjack was missing in the container and clippy has --all-features set, so it will certainly try to build with jack and not find it if not installed. How this could have worked before however is not clear to me.

2022-10-21 10:52 UTC, est31 requested changes

2022-10-21 10:52 UTC, est31 commented on Cargo.toml
> +nix = "^0.23"
Which crate is blocking the nix update? I think we should either depend on an older version of nix, or a newer version.

2022-10-21 12:04 UTC, mbodmer commented on Cargo.toml
> +nix = "^0.23"
alsa-rs has a dependency on 0.24, likely changing at some point in time. So right now we have a dependency on 0.23.1 (current CPAL) and 0.24 (current alsa-rs). To make this depend on the same version we can also change to 0.24 until alsa-rs changes this, then we will have a double dependency again. Or we give cargo a range and let it choose a common version for all if it can. The broader the range the better cargo can find a single common version. As nix is not very extensively used I think it's reasonable to support a broad range.

2022-10-21 12:11 UTC, est31 commented on Cargo.toml
> +nix = "^0.23"
The issue with ranges is that stuff might break on an update, which isn't really great. I'd prefer either staying on an old version of nix, or duplicating alsa-rs.

2022-10-21 12:19 UTC, mbodmer commented on Cargo.toml
> +nix = "^0.23"
Yeah, that's true. But it seemed the interface is very stable and thus shouldn't break that easy. But still it's a risk, fair enough. Should I set it to 0.24 as alsa-rs has? Or well, we know it's fine from 0.23.1 to 0.25, how about a range of these versions. Like: ">= 0.23.1, < 0.26" ?

2022-10-21 12:23 UTC, est31 commented on Cargo.toml
> +nix = "^0.23"
I think we should wait for https://github.com/diwic/alsa-rs/pull/89 for now, wait for a release, and then set it to 0.25. Alternatively, set it to whatever version the currently released alsa crate uses. If there is no release in a reasonable time frame, we can use a range instead like you suggested.

2022-10-21 12:26 UTC, mbodmer commented on Cargo.toml
> +nix = "^0.23"
I've just saw, it's not using 0.24, but 0.23 so I will revert the version to 0.23.1 and wait for alsa, you are right

2022-10-22 08:24 UTC, mbodmer commented
Ok, the nix version is back to where it was. The rest has a mergable state. From my side this PR is ready to merge. Thanks for reviewing.

2022-10-23 07:14 UTC, est31 commented
Currently we are blocked by: https://github.com/diwic/alsa-rs/issues/90

2022-10-23 10:12 UTC, mbodmer commented
Oh, didn't realize the mess this would start. CPAL now uses the alsa re-export of the nix::error since here: https://github.com/RustAudio/cpal/commit/16617ceadef0914ab14fc124354315afe63915fa
I did not understand the implications at that time however, just tried to fix the error I've got from the version change. See also: https://github.com/diwic/alsa-rs/issues/81#issuecomment-953689161

2022-10-23 10:53 UTC, mbodmer commented
I've now removed nix as a dependency, as It's not used anywhere anymore in CPAL.

2022-10-23 18:58 UTC, est31 approved these changes
Thanks!

2022-10-23 18:59 UTC, merged

2022-10-23 19:03 UTC, mbodmer commented
Thanks for merging :-) and sorry for the mess this caused, but for the good finally, imo