Improve asio sys build script
RustAudio/cpal pull request #809
Opened 2023-11-05 22:00 UTC by alisomay

# Improvements

- `vcvarsall.bat` is executed exhaustively for any supported host and target architecture combinations now. 
-  Downloading the ASIO SDK is working on all platforms now which enables cross compilation. 
-  A section on the `README.md` is added which explains cross compilation scenarios for `cpal` with the `asio` feature.
-  `vcvarsall.bat` search is improved greatly to execute smarter and faster to cover for CI scenarios where the disk I/O might be a bottle neck. 
-  A type mismatch bug which was apparent on using the `mingw-w64` tool chain is fixed. 

With these changes I want to enable:
- Better building experience in CI
- Improve existing changes to be cross compilation ready.

What I have tried:

- macOS aarch64 (host) -> windows x86, x86_64 (target) ✅ 
- linux (ubuntu) aarch64 (host) -> windows x86, x86_64 (target) ✅ 
- windows aarch64 (host)-> windows x86, x86_64, aarch64 (target) ✅ 
- windows x86_64 (host)-> windows x86, x86_64, aarch64 (target) ✅ 

If I missed something, I'll correct it along the way.
Thank you for the last merge, and I look forward to your review 🙏

2023-11-05 23:06 UTC, alisomay commented
I've also checked a bit about the reason why `asmjs-wasm32-test` fails the CI.
This snippet
```rust
#[cfg(target_os = "emscripten")]
impl wasm_bindgen::convert::IntoWasmAbi for BufferSize {
    type Abi = wasm_bindgen::convert::WasmOption<u32>;
    fn into_abi(self) -> Self::Abi {
        match self {
            Self::Default => None,
            Self::Fixed(fc) => Some(fc),
        }
        .into_abi()
    }
}
```
Has this type `wasm_bindgen::convert::WasmOption<u32>`.

But that type does not exist anymore in the [module](https://docs.rs/wasm-bindgen/latest/wasm_bindgen/convert/index.html).

The changes made to that snippet was 12 months ago and the last time I have checked the CI was green a few weeks ago. 

I wonder if my changes made a side effect..

2023-11-10 08:27 UTC, alisomay commented
No significant rush but when approximately you may look at this?
Thanks 🙏

2023-11-10 22:03 UTC, est31 requested changes

2023-11-10 22:03 UTC, est31 commented on asio-sys/Cargo.toml
> +
why these blank lines?

2023-11-10 22:03 UTC, est31 commented on asio-sys/build.rs
> +    let paths = vec![
this can just be a `&[...]` right?

2023-11-10 22:03 UTC, est31 commented on asio-sys/build.rs
> +    let arch_arg = if cfg!(target_arch = "x86_64") {
`target_arch` in a build script also refers to the arch of the host, as the build scripts are always compiled for the host.

2023-11-10 22:05 UTC, est31 commented
> I wonder if my changes made a side effect..

I don't think so.

> I don't know how it is used in the wild but this may provide a solution:

feel free to make a PR!

2023-11-10 22:51 UTC, alisomay commented on asio-sys/build.rs
> +    let arch_arg = if cfg!(target_arch = "x86_64") {
This is indeed confusing. I didn't catch that thanks!

Running this build script on macos `aarch64`
with the command `cargo build --target=x86_64-pc-windows-gnu` :

```rust
fn main() {
    let target_arch = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap();
    let host_architecture = std::env::consts::ARCH;

    if cfg!(target_arch = "x86_64") {
        println!(r#"cfg!(target_arch = "x86_64")"#);
    }

    if cfg!(target_arch = "aarch64") {
        println!(r#"cfg!(target_arch = "aarch64")"#);
    }

    println!(
        "CARGO_CFG_TARGET_ARCH: {}\nstd::env::consts::ARCH: {}",
        target_arch, host_architecture
    );

    panic!();
}
```
yields

```
  --- stdout
  cfg!(target_arch = "aarch64")
  CARGO_CFG_TARGET_ARCH: x86_64
  std::env::consts::ARCH: aarch64
```

which indeed proves the `target_arch` in the `cfg!` macro is actually the host arch from my point of view.

I'll apply the changes accordingly replacing those with the target arch parsed from the triple. 
I'll also double check if it uses`CARGO_CFG_*` variables. 
https://github.com/rust-lang/cargo/issues/4302

2023-11-10 22:52 UTC, alisomay commented on asio-sys/build.rs
> +    let paths = vec![
Probably it can. 👍

2023-11-10 22:52 UTC, alisomay commented on asio-sys/Cargo.toml
> +
Probably forgotten, I'll just remove them.

2023-11-11 11:25 UTC, alisomay commented on asio-sys/build.rs
> +    let arch_arg = if cfg!(target_arch = "x86_64") {
[2d6b063](https://github.com/RustAudio/cpal/pull/809/commits/2d6b063f68431030db0bed654ba597332f418e84)
Fixes it.

2023-11-11 11:26 UTC, alisomay commented on asio-sys/build.rs
> +    let paths = vec![
[2d6b063](https://github.com/RustAudio/cpal/pull/809/commits/2d6b063f68431030db0bed654ba597332f418e84)

2023-11-11 11:26 UTC, alisomay commented on asio-sys/Cargo.toml
> +
[2d6b063](https://github.com/RustAudio/cpal/pull/809/commits/2d6b063f68431030db0bed654ba597332f418e84)

2023-11-11 15:27 UTC, est31 approved these changes

2023-11-11 15:27 UTC, merged