ALSA PCM.try_recover: error handling
RustAudio/cpal pull request #909
Opened 2024-09-06 04:07 UTC by lautarodragan

When passing `silent=false` to PCM.try_recover, it'll write to `stderr` a detail of the error.

In this case, it's always `underrun occurred` or `overrun occurred`. It logs this even when successfully recovering. This is the relevant code in ALSA's GitHub mirror, as of now:

```c
        if (err == -EPIPE) {
                const char *s;
                if (snd_pcm_stream(pcm) == SND_PCM_STREAM_PLAYBACK)
                        s = "underrun";
                else
                        s = "overrun";
                if (!silent)
                        SNDERR("%s occurred", s);
                err = snd_pcm_prepare(pcm);
                if (err < 0) {
                        SNDERR("cannot recovery from %s, prepare failed: %s", s, snd_strerror(err));
                        return err;
                }
                return 0;
        }
```

By setting it to silent, we lose this detail (whether it was an under- or over-run). But letting it write directly to stderr is messing up my ratatui app :( and I don't think there's a standard, cross-platform, safe way to prevent anything from writing to std(out|err) in-process.

Failures in `try_handle` will now call `error_callback`, but these noisy `underrun occurred` always recovered successfully, in my case.

I guess we could also offer some sort of `#[cfg(feature = "alsa-silent-try_recover")]` or adding a run-time arg to the function chain all the way up to `build_output_stream` and then Rodio's `try_from_device`, or add it as an option in `struct StreamConfig`. Personally, I'd prefer avoiding the added code complexity of the run-time option, but I could see some value in the build-time option, if properly documented.

---

For context, I can consistently trigger these by calling Rodio's `sink.try_seek` too quickly (as fast as crossterm's `event::poll` will trigger it, while I hold down a key I'm mapping to `seek` in my app).

Silencing this error gets rid of the visual noise/glitches, but I still need to manage the sound glitches somehow. But that's probably on me for not debouncing calls to `seek` and/or using `OutputStream::try_default()` and not setting anything manually in `SupportedStreamConfig` (`buffer_size`, I guess).

2024-09-06 04:11 UTC, lautarodragan commented on src/host/alsa/mod.rs
> +                //   Even if these recover successfully, they still may cause audible glitches.
Is it `still may` or `may still`?

2024-09-06 05:38 UTC, Ralith requested changes
> I still need to manage the sound glitches somehow. But that's probably on me for not debouncing

It's probably rodio's fault.

2024-09-06 05:38 UTC, Ralith commented on src/host/alsa/mod.rs
> +                };
This is not real-time-safe, and doesn't seem to be related to the core intent of this PR. Maybe just drop it?

2024-09-06 15:00 UTC, lautarodragan commented on src/host/alsa/mod.rs
> +                };
Thanks for the review :heart: and change applied! I force-pushed in my branch to keep the PR clean — just 1 commit. 

I'm curious (and ignorant), though: what do you mean by _not rela-time safe_, exactly? Is calling the error_callback risking consuming a significant amount of CPU, such that it'd impact playback? More so than the other 2 branches that already do call `error_callback`?

2024-09-06 18:11 UTC, Ralith commented on src/host/alsa/mod.rs
> +                };
Calling `malloc` as you do by invoking `format` risks blocking the thread for an unpredictable duration, since it might e.g. acquire a lock or invoke `mmap` internally.

2024-09-06 18:27 UTC, lautarodragan commented on src/host/alsa/mod.rs
> +                };
Ah! Makes sense. Thanks. Not relevant to this PR, but I guess the best way around that (even if not particularly ergonomic) would be `error_callback(err_code: usize)`, if we did support that?

2024-09-06 21:09 UTC, Ralith commented on src/host/alsa/mod.rs
> +                };
Regular value types, like intelligible enum variants, are fine. Perhaps cpal shouldn't have that `description: String` field at all, though I expect it's currently mostly used in places where recovery is hopeless anyway.

2024-09-09 23:52 UTC, Ralith approved these changes

2024-09-09 23:52 UTC, Ralith commented on src/host/alsa/mod.rs
> +                //   (Both potentially not real-time-safe)
Calling the error callback is safe for our purposes. It's the user's responsibility to do real-time-safe things in their callbacks, or accept the risk of failing to.

2024-09-15 02:49 UTC, lautarodragan commented
@est31 I hope this isn't rude of me — so sorry of it is! But can you review/merge this, please? 🙏 

It's a super small change that adds a lot of value, at least in my use case, and possibly to all ratatui apps that use cpal.

2024-11-27 23:16 UTC, lautarodragan commented
@Ralith sorry to bother you but I'd love to have this one merged, if possible. 

Can you help me with that? I'm not sure who could review/merge this one, or whether there are some other changes I should address in this PR before it's mergeable.

2024-11-27 23:26 UTC, Ralith commented
It's up to @est31, I'm afraid.

2025-07-06 23:51 UTC, est31 commented
hi, can you resolve the conflicts?

2025-07-06 23:51 UTC, est31 commented
Sorry for the long wait, I don't have as much time as I used to.

2025-07-07 17:32 UTC, lautarodragan commented
> hi, can you resolve the conflicts?

Done!

> Sorry for the long wait, I don't have as much time as I used to.

No worries. Thank you for reviewing this, and for all the work you do for RustAudio, the let_chains standard and open source in general :pray:

2025-07-07 21:11 UTC, merged